// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdxAsPpNoJtTx4KvLucBAhs7KIud2qvdY',
    appId: '1:307158907280:web:227b0674037d8655d29b15',
    messagingSenderId: '307158907280',
    projectId: 'my-social-media-app4566',
    authDomain: 'my-social-media-app4566.firebaseapp.com',
    storageBucket: 'my-social-media-app4566.firebasestorage.app',
    measurementId: 'G-2EKG3KCPJS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6Ztm2pLVh4cV_oZHkPDOKYAIV9UQK9vU',
    appId: '1:307158907280:android:1c87522aec513f74d29b15',
    messagingSenderId: '307158907280',
    projectId: 'my-social-media-app4566',
    storageBucket: 'my-social-media-app4566.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBITzSm9738_RFOHyM3Pu8dzn3gWsSHeHs',
    appId: '1:307158907280:ios:e38ded882ef01b76d29b15',
    messagingSenderId: '307158907280',
    projectId: 'my-social-media-app4566',
    storageBucket: 'my-social-media-app4566.firebasestorage.app',
    iosBundleId: 'com.microcode.socialMediaApp',
  );
}
